baseURL = 'https://dominicfox.com/'
languageCode = 'en-us'
title = 'Dominic Fox'
theme = "LoveIt"

[params.home.profile]
title = 'Dominic Fox'
subtitle = 'Dominic is a writer, musician, and software developer living in London, UK'
typeit = false

[params.header.title]
name = "Dominic Fox"

[params.footer]
hugo = false

[params.social]
twitter = "dynamic_proxy"
facebook = "reynardine"
instagram = "codepoetics"
github = "poetix"

[menu]
  [[menu.main]]
  weight = 1
  identifier = "vulpuslabs"
  name = "vulpus labs"
  url = "/vulpuslabs"

  [[menu.main]]
  weight = 1
  identifier = "publications"
  name = "publications"
  url = "/publications"

  [[menu.main]]
  weight = 1
  identifier = "music"
  name = "music"
  url = "/music"
